import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
 
import Link from 'next/link'

export default function Home() {
  return (
     <>
      <Head>
        <title>Onlinai kursai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1 className={styles.title}>Sveiki atvyke </h1>
        <p className={styles.text}> Šitame psulapyje galėsite rasti visokiausiu online kursų .</p>
        
        <Link href="/coursess/">
          <a className={styles.btn}>Spauskite cia kad pamatytumet kursus</a>
        </Link>
      </div>
    </>
  )
}